# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_FSNOTIFY)		+= fsnotify.o notification.o group.o mark.o \
				   fdinfo.o
ccflags-y		:= -fno-lto
obj-y			+= dnotify/
obj-y			+= inotify/
obj-y			+= fanotify/
